default:
	rm -Rf stage/libifconfig
	mkdir -p stage/libifconfig
	$(CC) -std=gnu99 -Wall -Wextra -Werror -fPIC -shared -o stage/libifconfig/libifconfig.so src/libifconfig.c src/libifconfig_internal.c
	cp src/libifconfig.h stage/libifconfig/
clean:
	rm -Rf stage
doxygen:
	rm -Rf stage/doxygen
	mkdir -p stage/doxygen
	doxygen tools/Doxyfile
