# $FreeBSD$

PACKAGE=	lib${LIB}
LIB=		ifc

SHLIBDIR?=	/lib
SHLIB_MAJOR=	1
SRCS=		libifc.c libifc_internal.c

INCSDIR=	${INCLUDEDIR}
INCS=		libifc.h

#MAN=		libifco.3

CFLAGS+= -I${.CURDIR}

.include <bsd.lib.mk>
