# $FreeBSD$

PACKAGE=lib${LIB}
LIB=    ifconfig

SHLIBDIR?= /lib
SHLIB_MAJOR= 1
SRCS=   src/libifconfig.c src/libifconfig_internal.c

INCSDIR=	${INCLUDEDIR}/libifconfig
INCS=   src/libifconfig.h

#MAN=    libifconfig.3

CFLAGS+=-I${.CURDIR}

.include <bsd.lib.mk>
