default:
	rm -Rf stage/libifc
	mkdir -p stage/libifc
	$(CC) -Wall -fPIC -shared -o stage/libifc/libifc.so src/libifc.c src/libifc_internal.c
	cp src/libifc.h stage/libifc/
clean:
	rm -Rf stage
doxygen:
	rm -Rf stage/doxygen
	mkdir -p stage/doxygen
	doxygen tools/Doxyfile
